### ISSUE TITLE
use https://registers.cloudapps.digital/registers/government-organisation

### ISSUE THREAD

**Issue by techforevil** [techforevil/service-catalogue#11]

**Comment by jonodrew** [comment]
Use it for what?

**Comment by techforevil** [comment]
Uh, not sure, mostly thought it would be nice to use it. 😳

It's a shame the register does not have hierarchy, that would really come in handy and could do some neat stuff to easily attribute things to HMPO 'within' HO etc. 

Maybe like, get the org name + link to gov.uk from the register to create a page for it (where we can also link to their github organisation page). 

Any better ideas? :)
